spring.application.name=libreria-springboot

# CONFIGURACION DE BD
spring.datasource.url=jdbc:postgresql://localhost:5432/libreriadb
spring.datasource.username=postgres
spring.datasource.password=p4tr0c1n14
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect